### PR TITLE
Migrate fabric to use Fabric API dynamic registries (also bump versions)

### PR DESCRIPTION
**Pull request by Linguardium**
bump version to 5.0.0.3
Update loom to 1.5+
Update fabric loader 0.15.3
Update fabric api version to 0.92.1
Update forge to 6.0+
Update registrationutils to 1.0.1
Fabric:
Migrate to FAPI Dynamic registries
Remove unnecessary mixin
Add mixin for registry path to match original (remove namespace)

### CODE REVIEW

**Comment by Linguardium** [comment]
fixes #171 
fixes #174
fixes #187 
fixes #194

**Comment by abidbmt** [comment]
Issue persists with identical crash report: https://gist.github.com/abidbmt/f6fce0270db842066af7598dee6413e2

**Comment by Linguardium** [comment]
> Issue persists with identical crash report: https://gist.github.com/abidbmt/f6fce0270db842066af7598dee6413e2

> enhancedcelestials: Enhanced Celestials 5.0.0.2

because you arent using the modified version...

**Comment by abidbmt** [comment]
> > Issue persists with identical crash report: https://gist.github.com/abidbmt/f6fce0270db842066af7598dee6413e2
> 
> > enhancedcelestials: Enhanced Celestials 5.0.0.2
> 
> because you arent using the modified version...

Oh i see, apparently the fix wasnt released to curseforge yet

**Comment by CorgiTaco** [comment]
@Linguardium Thank you so much. Been so busy haven't had a chance. 

This change is now pushed to Curseforge + Modrinth for 5.0.0.3+. CC @abidbmt

**Comment by abidbmt** [comment]
@CorgiTaco Great thank you!

**Pull request merged**
